services:
    timomf.bbclone_ext.listener:
        class: timomf\bbclone_ext\event\listener
        arguments:
            - @config
            - @template
            - @request
            - @user
            - @auth
        tags:
            - { name: event.listener }